version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build \
              --no-cache \
              -t coredump/mattermost-push-proxy:latest \
              -t coredump/mattermost-push-proxy:${CIRCLE_BRANCH} \
              .
      - deploy:
          name: Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_API_KEY && \
            docker push coredump/mattermost-push-proxy
workflows:
  version: 2

  # Build on push to docker branch
  on_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - docker

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - docker
    jobs:
      - build
